# Generated by Django 2.1.7 on 2019-03-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('assortment', models.CharField(max_length=50)),
                ('visitors', models.IntegerField()),
                ('pubDate', models.DateField()),
                ('modifyDate', models.DateField()),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('alt', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
    ]
